using System;
using System.Collections.Generic;
using System.Linq;

namespace CoffeeManager.Models.Class
{
    /// <summary>
    /// Provides reporting utilities for sales, products, employees and warehouse usage. (≧◡≦) ZORRODEV2026
    /// </summary>
    internal class ReportService
    {
        #region DAILY REPORTS (≧◡≦)

        /// <summary>
        /// Returns all sales made on a specific date. (≧◡≦)
        /// </summary>
        public List<Sale> GetDailySales(Store store, DateTime date)
        {
            return store.Sales.Where(s => s.Date.Date == date.Date).ToList();
        }

        /// <summary>
        /// Calculates total revenue for a specific date. (≧◡≦)
        /// </summary>
        public decimal GetDailyRevenue(Store store, DateTime date)
        {
            return GetDailySales(store, date).Sum(s => s.Total);
        }

        /// <summary>
        /// Calculates total cost of production for a specific date. (≧◡≦)
        /// </summary>
        public decimal GetDailyCost(Store store, DateTime date)
        {
            decimal total = 0m;

            foreach (var sale in GetDailySales(store, date))
            {
                foreach (var detail in sale.Details)
                {
                    var product = detail.Product;
                    if (product == null) continue;

                    total += product.GetUnitCost(store.Warehouse) * detail.Quantity;
                }
            }

            return total;
        }

        /// <summary>
        /// Calculates net profit for a specific date. (≧◡≦)
        /// </summary>
        public decimal GetDailyProfit(Store store, DateTime date)
        {
            return GetDailyRevenue(store, date) - GetDailyCost(store, date);
        }

        #endregion


        #region EMPLOYEE REPORTS (✧ω✧)

        /// <summary>
        /// Returns all sales made by a specific employee. (≧◡≦)
        /// </summary>
        public List<Sale> GetSalesByEmployee(Store store, int employeeId)
        {
            return store.Sales.Where(s => s.EmployeeId == employeeId).ToList();
        }

        /// <summary>
        /// Calculates total revenue generated by an employee. (≧◡≦)
        /// </summary>
        public decimal GetEmployeeRevenue(Store store, int employeeId)
        {
            return GetSalesByEmployee(store, employeeId).Sum(s => s.Total);
        }

        #endregion


        #region PRODUCT REPORTS (ง'̀-'́)ง

        /// <summary>
        /// Returns total quantity sold of a specific product. (≧◡≦)
        /// </summary>
        public int GetProductUnitsSold(Store store, int productId)
        {
            return store.Sales
                .SelectMany(s => s.Details)
                .Where(d => d.ProductId == productId)
                .Sum(d => d.Quantity);
        }

        /// <summary>
        /// Returns a ranking of products by units sold. (≧◡≦)
        /// </summary>
        public List<(Product Product, int UnitsSold)> GetBestSellingProducts(Store store)
        {
            return store.Products
                .Select(p => (Product: p, UnitsSold: GetProductUnitsSold(store, p.Id)))
                .OrderByDescending(x => x.UnitsSold)
                .ToList();
        }

        #endregion


        #region WAREHOUSE USAGE (◕‿◕✿)

        /// <summary>
        /// Returns total usage of each warehouse ingredient based on all sales. (≧◡≦)
        /// </summary>
        public Dictionary<string, decimal> GetIngredientUsage(Store store)
        {
            var usage = new Dictionary<string, decimal>();

            foreach (var sale in store.Sales)
            {
                foreach (var detail in sale.Details)
                {
                    var product = detail.Product;
                    if (product == null || !product.UsesWarehouse) continue;

                    foreach (var ingredient in product.Recipe)
                    {
                        var totalUsed = ingredient.Quantity * detail.Quantity;

                        if (!usage.ContainsKey(ingredient.IngredientName))
                            usage[ingredient.IngredientName] = 0;

                        usage[ingredient.IngredientName] += totalUsed;
                    }
                }
            }

            return usage;
        }

        #endregion


        #region FINAL DAILY REPORT ( ZORRODEV2026 (✿◠‿◠) )

        /// <summary>
        /// Generates a full daily report in text format. (≧◡≦)
        /// </summary>
        public string GenerateDailyReport(Store store, DateTime date)
        {
            var sales = GetDailySales(store, date);
            var revenue = GetDailyRevenue(store, date);
            var cost = GetDailyCost(store, date);
            var profit = revenue - cost;

            var bestProducts = GetBestSellingProducts(store);
            var usage = GetIngredientUsage(store);

            string report = "";
            report += "==============================\n";
            report += $" COFFEE MANAGER DAILY REPORT\n";
            report += $" DATE: {date:yyyy-MM-dd}\n";
            report += "==============================\n\n";

            report += $"Total Sales: {sales.Count}\n";
            report += $"Revenue: ${revenue:F2}\n";
            report += $"Cost: ${cost:F2}\n";
            report += $"Profit: ${profit:F2}\n";
            report += $"Losses: ${store.TotalLosses:F2}\n";
            report += $"Waste: ${store.TotalWaste:F2}\n\n";

            report += "---- BEST SELLING PRODUCTS ----\n";
            foreach (var item in bestProducts)
                report += $"{item.Product.Name}: {item.UnitsSold} sold\n";

            report += "\n---- INGREDIENT USAGE ----\n";
            foreach (var u in usage)
                report += $"{u.Key}: {u.Value}\n";

            report += "\n==============================\n";
            report += " END OF REPORT (≧◡≦)\n";
            report += "==============================\n";

            return report;
        }

        #endregion
    }
}
