using System;
using System.Collections.Generic;
using System.Linq;
using CoffeeManager.Models.Class;

namespace CoffeeManager.Services
{
    /// <summary>
    /// Provides analytical and reporting features for the CoffeeManager system.
    /// Works with Store to generate summaries, statistics and insights. (ง'̀-'́)ง ZORRODEV2026
    /// </summary>
    internal class ReportService
    {
        #region STORE REFERENCE (≧◡≦)

        /// <summary>
        /// Reference to the main store containing products, employees and sales. (✿◠‿◠)
        /// </summary>
        private readonly Store _store;

        /// <summary>
        /// Creates a new instance of ReportService using the provided store. (◕‿◕✿)
        /// </summary>
        public ReportService(Store store)
        {
            _store = store;
        }

        #endregion

        #region SALES REPORTS (ง'̀-'́)ง

        /// <summary>
        /// Returns all sales made on a specific date. (≧◡≦)
        /// </summary>
        public List<Sale> GetSalesByDate(DateTime date)
        {
            return _store.Sales.Where(x => x.Date.Date == date.Date).ToList();
        }

        /// <summary>
        /// Returns all sales made between two dates. (✧ω✧)
        /// </summary>
        public List<Sale> GetSalesBetween(DateTime start, DateTime end)
        {
            return _store.Sales
                .Where(x => x.Date.Date >= start.Date && x.Date.Date <= end.Date)
                .ToList();
        }

        /// <summary>
        /// Returns the total revenue between two dates. (◕‿◕✿)
        /// </summary>
        public decimal GetTotalRevenue(DateTime start, DateTime end)
        {
            return GetSalesBetween(start, end).Sum(x => x.Total);
        }

        /// <summary>
        /// Returns the average ticket amount between two dates. (ಠ‿ಠ)
        /// </summary>
        public decimal GetAverageTicket(DateTime start, DateTime end)
        {
            var sales = GetSalesBetween(start, end);
            return sales.Count == 0 ? 0 : sales.Average(x => x.Total);
        }

        #endregion

        #region EMPLOYEE REPORTS (≧◡≦)

        /// <summary>
        /// Returns all sales made by a specific employee. (✿◠‿◠)
        /// </summary>
        public List<Sale> GetSalesByEmployee(int employeeId)
        {
            return _store.Sales.Where(x => x.EmployeeId == employeeId).ToList();
        }

        /// <summary>
        /// Returns the total revenue generated by a specific employee. (✧ω✧)
        /// </summary>
        public decimal GetEmployeeRevenue(int employeeId)
        {
            return GetSalesByEmployee(employeeId).Sum(x => x.Total);
        }

        /// <summary>
        /// Returns employees ordered by total revenue generated. (◕‿◕✿)
        /// </summary>
        public List<(Employee Employee, decimal Total)> GetEmployeeRanking()
        {
            return _store.Employees
                .Select(e => (e, GetEmployeeRevenue(e.Id)))
                .OrderByDescending(x => x.Item2)
                .ToList();
        }

        #endregion

        #region PRODUCT REPORTS (ง'̀-'́)ง

        /// <summary>
        /// Returns total quantity sold for a specific product. (≧◡≦)
        /// </summary>
        public int GetProductUnitsSold(int productId)
        {
            return _store.Sales
                .SelectMany(s => s.Details)
                .Where(d => d.ProductId == productId)
                .Sum(d => d.Quantity);
        }

        /// <summary>
        /// Returns products ordered by units sold. (✧ω✧)
        /// </summary>
        public List<(Product Product, int Units)> GetTopSellingProducts()
        {
            return _store.Products
                .Select(p => (p, GetProductUnitsSold(p.Id)))
                .OrderByDescending(x => x.Item2)
                .ToList();
        }

        /// <summary>
        /// Returns products with zero sales. (ಠ‿ಠ)
        /// </summary>
        public List<Product> GetUnsoldProducts()
        {
            return _store.Products
                .Where(p => GetProductUnitsSold(p.Id) == 0)
                .ToList();
        }

        #endregion

        #region INVENTORY REPORTS (◕‿◕✿)

        /// <summary>
        /// Returns products with stock below the specified threshold. (≧◡≦)
        /// </summary>
        public List<Product> GetLowStockProducts(int threshold)
        {
            return _store.Products.Where(p => p.Stock <= threshold).ToList();
        }

        #endregion
    }
}
